services:
 wdio:
  build: .
  volumes: 
   - /webdriverio/wdio.conf.js
   - /webdriverio/test
   - /webdriverio/node_modules
   - /webdriverio/results
  depends_on:
   - selenium
 selenium:
  image: selenium/standalone-chrome
  ports:
   - 4444:4444