services:
 wdio:
  build: .
  volumes: 
   - $PWD/wdio.conf.js:/webdriverio/wdio.conf.js
   - $PWD/test:/webdriverio/test
   - $PWD/node_modules:/webdriverio/node_modules
   - $PWD/results:/webdriverio/results
  depends_on:
   - selenium
 selenium:
  image: selenium/standalone-chrome
  ports:
   - 4444:4444